version: "3.5"

services:
  drone-dispatcher:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/musala-task?serverTimezone=UTC
      - MYSQL_USER=musala-test
      - MYSQL_PASSWORD=musala-test
  db:
     image: mysql:8.0
     ports:
       - "3306:3306"
     environment:
         - MYSQL_DATABASE=musala-task
         - MYSQL_USER=musala-test
         - MYSQL_PASSWORD=musala-test
         - MYSQL_ROOT_PASSWORD=Abimbola1981&
         - MYSQL_ALLOW_EMPTY_PASSWORD=true

