--DROP TABLE IF EXISTS DRONE;
--DROP TABLE IF EXISTS MEDICATION;
--DROP TABLE IF EXISTS DRONE_MEDICATION;

CREATE TABLE DRONE( ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                       SERIAL_NO VARCHAR(100) NOT NULL,
                       MODEL VARCHAR(100),
                       WEIGHT_LIMIT INTEGER NOT NULL,
                       BATTERY_CAPACITY DECIMAL NOT NULL,
                       STATE SMALLINT NOT NULL
                       );
CREATE TABLE MEDICATION(ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                        NAME VARCHAR(300) NOT NULL UNIQUE,
                        WEIGHT DECIMAL NOT NULL,
                        CODE VARCHAR(200) NOT NULL UNIQUE,
                        IMAGE_URL varchar(max) NOT NULL
                        );

CREATE TABLE DRONE_MEDICATION(
CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
DRONE_ID INTEGER NOT NULL,
MEDICATION_ID INTEGER NOT NULL,
 FOREIGN KEY(DRONE_ID) REFERENCES DRONE(ID),
 FOREIGN KEY(MEDICATION_ID) REFERENCES MEDICATION(ID)
);

